# Generated by Django 5.0.4 on 2024-04-22 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_post_post_shortname_alter_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post/images/'),
            preserve_default=False,
        ),
    ]
